version: "3"
services: 
  app:
    build: ./app/
    image: recs-api:latest 
    container_name: recs-api
    restart: unless-stopped
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - recs-network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
  ml_worker:
    build: ./ml_worker/
    image: recs-ml-worker:latest
    restart: unless-stopped
    env_file:
    - ./app/.env
    volumes:
      - ./ml_worker:/app
      - ./app/models:/app/models
      - ./app/database:/app/database
      - ./app/services/crud:/app/services/crud
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - recs-network
    deploy:
      mode: replicated
      replicas: 3
  web:
    image: nginx:latest
    container_name: recs-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - recs-network
  db:
    image: postgres:16-alpine
    container_name: recs-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - recs-network
  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"  # Management UI
      - "5672:5672"    # AMQP protocol
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 20s
      timeout: 10s
      retries: 30
    networks:
      - recs-network
  streamlit_ui:
    build: ./streamlit_ui/
    image: streamlit-ui:latest
    container_name: recs-streamlit
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_ui:/app
    depends_on:
      - app
    networks:
      - recs-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  recs-network:
    name: recs-network
    driver: bridge
